<?xml version="1.0" encoding="UTF-8"?>
<tabledefine storagename="DemoPersonInfo" ID="AD59705C97A240FA87F382DEEB9B937C" name-db="DemoPersonInfo" category="" title="" author="" description="" packagename="com.jiuqi.xuheyao.dna.demo.storage" name="DemoPersonInfo" isneedrebuild="false">
	<fields>
		<field dbtable="DemoPersonInfo" name="personName" name-db="personName" type="nvarchar(20)" primary-key="false" keep-valid="false" author="" title="" description="" ID="C0E71E84285BCA5C1E9693067EC93926"/>
		<field dbtable="DemoPersonInfo" name="personAge" name-db="personAge" type="int" primary-key="false" keep-valid="false" author="" title="" description="" ID="166E46264653387B48C8B1460D5DFFD5"/>
		<field dbtable="DemoPersonInfo" name="personSex" name-db="personSex" type="varchar(4)" primary-key="false" keep-valid="false" author="" title="" description="" ID="E1376482DC5B445C246F7581066DA63F"/>
		<field dbtable="DemoPersonInfo" name="personDate" name-db="personDate" type="date" primary-key="false" keep-valid="false" author="" title="" description="" ID="55A4BF7CF7AA31C5B26411CD252940B0"/>
		<field dbtable="DemoPersonInfo" name="personDept" name-db="personDept" type="guid" primary-key="false" keep-valid="false" author="" title="" description="" ID="4FB2724ABF12AA30A130ACF2C5A2C758"/>
		<field dbtable="DemoPersonInfo" name="personDesc" name-db="personDesc" type="text" primary-key="false" keep-valid="false" author="" title="" description="" ID="AFE01208CCB5924261D8451053A050ED"/>
	</fields>
	<indexs/>
	<hierarchies/>
	<dbtables>
		<dbtable author="" name="DemoPersonInfo" name-db="DemoPersonInfo" title="" description=""/>
	</dbtables>
	<relations/>
</tabledefine>
